### PR TITLE
User views, controller, and routes without the UcbRailsUser namespace

### PR DESCRIPTION
**Pull request by brandondrew**
Because of [a Portal bug report](https://trello.com/c/HFH6Ppwy) that initially appeared to be very simple and easy to fix, I discovered a much more complicated problem of a mismatch between Portal and UCB Rails User with regards to namespacing of all things related to users.  While we have already removed the `UcbRailsUser` namespace for the `User` model, and changed the way it is handled for concerns, it still remained in the `usb_rails_user` gem for:

- all user views
- the users_controller
- user routes

As I made each change I did so with no apparent alternative.  Each change appeared to me at the time to be the only way to fix the problem in Portal (either the intial problem in the bug report or the one that was uncovered by the change I made to fix the previous one).  

At first this looked like it would involve removing the `UcbRailsUser` namespace everywhere, but I realized that could be avoided, and reverted all changes not related to the user.  So this pull request does not make changes to namespacing of impersonation or sessions or anything else.  However that could be done if we decide that it's desirable.  

My goal here was to make the minimal change that would solve my problem in Portal.  Having gotten everything working, I can now see a small possibility of being able to get things working with slightly less of a change to the gem, but I would argue that making everything related to the user consistent and not namespaced makes everything much more straightforward and is therefore preferable. 

In addition there are 2 small commits dealing with peripheral things.  I can remove one or both of those if desired.  I rebased to make them the most recent commits and therefore easier to remove if that is preferable.  Also, I tried to follow local commit conventions as much as possible.  Let me know if you would like any changes.

### CODE REVIEW

**Comment by brandondrew** [comment]
See also: https://github.com/ucb-ist-eas/rsp/pull/308

**Comment by darinwilson** [comment]
I'm not 100% sure about this. Strictly speaking, it's not that we removed the `UcbRailsUser` namespace from the `User` model, but rather deferred the class constant to a host-app-configurable value. So currently in this gem, you don't see `User` but rather `UcbRailsUser.user_class`. This defaults to `User` but can be overridden if needed.

Specifically, I feel a little uncomfortable having this gem provide things that are not namespaced with `UcbRailsUser` as that introduces the potential to interfere with the host app in a way that could be difficult to override. It might be good to look at some other Rails engines to see how they handle it. But I can't think of any gem I've ever seen that wasn't namespaced.

**Comment by darinwilson** [comment]
@brandondrew OK if I close this out? I think we decided to go another way with this

**Comment by darinwilson** [comment]
Closing this as we're moving the repo to Gitlab

**Pull request closed without merging**
